export const featuredItems = [
     {
       name: 'John Doe',
       username: 'johndoe',
       profileImg: './assets/img/profiles/1.jpg',
       fallback: 'JD',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Jane Doe',
       username: 'janedoe',
       profileImg: './assets/img/profiles/2.jpg',
       fallback: 'JD',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Bakary Jallow',
       username: 'bakaryjallow',
       profileImg: './assets/img/profiles/3.jpg',
       fallback: 'BJ',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Alice Smith',
       username: 'alicesmith',
       profileImg: './assets/img/profiles/4.jpg',
       fallback: 'AS',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Bob Johnson',
       username: 'bobjohnson',
       profileImg: './assets/img/profiles/5.jpg',
       fallback: 'BJ',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Eva Martinez',
       username: 'evamartinez',
       profileImg: './assets/img/profiles/6.jpg',
       fallback: 'EM',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'David Wilson',
       username: 'davidwilson',
       profileImg: './assets/img/profiles/7.jpg',
       fallback: 'DW',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Grace Brown',
       username: 'gracebrown',
       profileImg: './assets/img/profiles/8.jpg',
       fallback: 'GB',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Michael Lee',
       username: 'michaellee',
       profileImg: './assets/img/profiles/9.jpg',
       fallback: 'ML',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
     {
       name: 'Sophia Davis',
       username: 'sophiadavis',
       profileImg: './assets/img/profiles/10.jpg',
       fallback: 'SD',
       bio: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
     },
   ];
   