import type { Metadata } from 'next'
import Navbar from '@/components/navbar/navbar'
import { ScrollArea } from '@/components/ui/scroll-area'

export const metadata: Metadata = {
  title: 'FalseNotes',
  description: 'Generated by create next app',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
     <Navbar />
            <ScrollArea className='h-screen max-w-screen xl:px-36 2xl:px-64'>
              <div className='py-24 px-4 md:px-24'>
                {children}
              </div>
            </ScrollArea>
    </>
  )
}
